# Site settings
title: Awesome
email: alireza.akrami@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  made with jekyll and github.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://akrami.github.io" # the base hostname & protocol for your site
twitter_username: xarax
github_username:  akrami

# Build settings
markdown: kramdown
highlighter: pygments
safe: true
lsi: false
