excerpt_separator: <!--more-->
title: Alireza Akrami
email: alireza@akrami.io
description: >- 
  
baseurl: ""
url: "https://alireza.akrami.io"
twitter_username: alirezatech
linkedin_username: iakrami
github_username: akrami

safe: true
encoding: utf-8
permalink: /:categories/:title
markdown: kramdown
timezone: Europe/Berlin
