excerpt_separator: <!--more-->
title: Alireza Akrami
email: alireza.akrami@outlook.com
description: >- 
  
baseurl: ""
url: "https://alireza.akrami.io"
twitter_username: alireza_tech
github_username: akrami

safe: true
encoding: utf-8
permalink: /:categories/:title
markdown: kramdown
timezone: Europe/Berlin
